context.properties = {
    core.daemon                 = true
    core.name                   = pipewire-0
    default.clock.rate          = 48000
    default.clock.allowed-rates = [48000]
    default.clock.quantum       = 512
    default.clock.min-quantum   = 512
    default.clock.max-quantum   = 1024
    default.clock.quantum-limit = 8192
    link.max-buffers            = 32
    module.x11.bell             = true
    module.access               = true
    module.jackdbus-detect      = true
    vm.overrides                = { default.clock.min-quantum = 512 }
}

context.spa-libs = {
    audio.convert.* = audioconvert/libspa-audioconvert
    avb.* = avb/libspa-avb
    api.alsa.* = alsa/libspa-alsa
    api.v4l2.* = v4l2/libspa-v4l2
    api.libcamera.* = libcamera/libspa-libcamera
    api.bluez5.* = bluez5/libspa-bluez5
    api.vulkan.* = vulkan/libspa-vulkan
    api.jack.* = jack/libspa-jack
    support.* = support/libspa-support
}

context.modules = [
    { name = libpipewire-module-rt 
      args = { nice.level = -2 rt.prio = 50 } 
      flags = [ ifexists nofail ] 
    }
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-profiler }
    { name = libpipewire-module-metadata }
    { name = libpipewire-module-spa-device-factory }
    { name = libpipewire-module-spa-node-factory }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-client-device }
    { name = libpipewire-module-portal flags = [ ifexists nofail ] }
    { name = libpipewire-module-access condition = [ { module.access = true } ] }
    { name = libpipewire-module-adapter }
    { name = libpipewire-module-link-factory }
    { name = libpipewire-module-session-manager }
    { name = libpipewire-module-x11-bell 
      flags = [ ifexists nofail ] 
      condition = [ { module.x11.bell = true } ] 
    }
    { name = libpipewire-module-jackdbus-detect 
      flags = [ ifexists nofail ] 
      condition = [ { module.jackdbus-detect = true } ] 
    }
]

context.objects = [
    { factory = spa-node-factory
      args = {
          factory.name            = api.alsa.pcm.sink
          node.name               = HighQuality-Sink
          node.description        = "ALSA Output (Low-Latency)"
          audio.format            = "S32LE"
          audio.rate              = 48000
          audio.channels          = 2
          resample.quality        = 10
          channelmix.normalize    = false
          channelmix.upmix        = false
          channelmix.upmix-method = psd
          node.latency            = 512/48000
      }
    }
    { factory = spa-node-factory
      args = {
          factory.name     = api.alsa.pcm.source
          node.name        = HighQuality-Source
          node.description = "ALSA Input (Low-Latency)"
          audio.format     = "S32LE"
          audio.rate       = 48000
          audio.channels   = 2
          resample.quality = 10
          node.latency     = 512/48000
      }
    }
]

alsa.properties = {
    alsa.access        = [ MMAP_INTERLEAVED MMAP_NONINTERLEAVED ]
    alsa.format        = [ "S32LE" "F32LE" ]
    alsa.rate          = { min=48000 max=48000 }
    alsa.channels      = { min=2 max=2 }
    alsa.period-bytes  = { min=2048 max=65536 }
    alsa.buffer-bytes  = { min=8192 max=131072 }
    alsa.volume-method = "physical"
}

context.exec = []

pulse.cmd = [
    { cmd = "load-module" args = "module-always-sink" flags = [] }
]

stream.properties = {
    node.latency   = 512/48000
    dither.method  = "shibata"
}

pulse.properties = {
    server.address = ["unix:native"]
    vm.overrides   = { pulse.min.quantum = 512/48000 }
}

pulse.rules = [
    { matches = [] actions = {} }
]